name: Latest Hashnode Blogs
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  blogs:
    name: latest hashnode blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE-BLOG-LIST"
          feed_list: "https://sandiphalder.hashnode.dev/"
